var recargaRasca_lista_blanca_planes_505 = [
	{codigoPlan: "M2", tipo: "INACTIVO"},
	{codigoPlan: "M3", tipo: "INACTIVO"},
	{codigoPlan: "M4", tipo: "INACTIVO"},
	{codigoPlan: "M5", tipo: "INACTIVO"},
	{codigoPlan: "M6", tipo: "INACTIVO"},
	{codigoPlan: "M7", tipo: "INACTIVO"},
	{codigoPlan: "M8", tipo: "INACTIVO"},
	{codigoPlan: "N1", tipo: "INACTIVO"},
	{codigoPlan: "N2", tipo: "INACTIVO"},
	{codigoPlan: "N5", tipo: "INACTIVO"},
	{codigoPlan: "N6", tipo: "INACTIVO"},
	{codigoPlan: "O0", tipo: "INACTIVO"},
	{codigoPlan: "O1", tipo: "INACTIVO"},
	{codigoPlan: "O2", tipo: "INACTIVO"},
	{codigoPlan: "O3", tipo: "INACTIVO"},
	{codigoPlan: "O4", tipo: "INACTIVO"},
	{codigoPlan: "O5", tipo: "INACTIVO"},
	{codigoPlan: "O6", tipo: "INACTIVO"},
	{codigoPlan: "O7", tipo: "INACTIVO"},
	{codigoPlan: "O8", tipo: "INACTIVO"},
	{codigoPlan: "Q0", tipo: "INACTIVO"},
	{codigoPlan: "Q1", tipo: "INACTIVO"},
	{codigoPlan: "Q2", tipo: "INACTIVO"},
	{codigoPlan: "Q3", tipo: "INACTIVO"},
	{codigoPlan: "Q4", tipo: "INACTIVO"},
	{codigoPlan: "Q5", tipo: "INACTIVO"},
	{codigoPlan: "Q6", tipo: "INACTIVO"},
	{codigoPlan: "Q7", tipo: "INACTIVO"},
	{codigoPlan: "Q8", tipo: "INACTIVO"},
	{codigoPlan: "R0", tipo: "INACTIVO"},
	{codigoPlan: "R1", tipo: "INACTIVO"},
	{codigoPlan: "R2", tipo: "INACTIVO"},
	{codigoPlan: "R3", tipo: "INACTIVO"},
	{codigoPlan: "R4", tipo: "INACTIVO"},
	{codigoPlan: "R5", tipo: "INACTIVO"},
	{codigoPlan: "R6", tipo: "INACTIVO"},
	{codigoPlan: "R7", tipo: "INACTIVO"},
	{codigoPlan: "R8", tipo: "INACTIVO"},
	{codigoPlan: "B0", tipo: "INDIVIDUAL CUENTA CONTROLADA"},
	{codigoPlan: "B1", tipo: "TARIFA UNICA CUENTA CONTROLADA"},
	{codigoPlan: "B2", tipo: "TARIFA UNICA CUENTA CONTROLADA"},
	{codigoPlan: "B3", tipo: "TARIFA UNICA CUENTA CONTROLADA"},
	{codigoPlan: "GD", tipo: "PREPAGO FIJO (F)"},
	{codigoPlan: "C1", tipo: "INDIVIDUAL CUENTA CONTROLADA"},
	{codigoPlan: "C2", tipo: "INDIVIDUAL CUENTA CONTROLADA"},
	{codigoPlan: "C3", tipo: "INDIVIDUAL CUENTA CONTROLADA"},
	{codigoPlan: "D0", tipo: "INDIVIDUAL CUENTA CONTROLADA"},
	{codigoPlan: "GA", tipo: "INDIVIDUAL CUENTA CONTROLADA"},
	{codigoPlan: "GB", tipo: "INDIVIDUAL CUENTA CONTROLADA"},
	{codigoPlan: "GC", tipo: "INDIVIDUAL CUENTA CONTROLADA"},
	{codigoPlan: "S0", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "S1", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "S2", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "S3", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "S4", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "S5", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "S6", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "S7", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "S8", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "S9", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "SA", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "SB", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "SC", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "SD", tipo: "PREPAGO TARIFA UNICA PROMO"},
	{codigoPlan: "SE", tipo: "PREPAGO INTERIOR"},
	{codigoPlan: "SF", tipo: "PREPAGO FULL"},
	{codigoPlan: "SG", tipo: "PREPAGO LIBRE PAQUETIZADO"},
	{codigoPlan: "SH", tipo: "PREPAGO FIJO FULL"},
	{codigoPlan: "SI", tipo: "PREPAGO FULL PAQUETIZADO"},
	{codigoPlan: "SJ", tipo: "PREPAGO TRIBU MOVISTAR"},
	{codigoPlan: "SK", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "SL", tipo: "INACTIVO"},
	{codigoPlan: "SM", tipo: "CC PYME COMPARTIDO A 0.065, 0.15"},
	{codigoPlan: "SN", tipo: "EMPRESA CUENTA CONTROLADA $0.10"},
	{codigoPlan: "SO", tipo: "EMPRESA CONTROLADA $0.06/0.14"},
	{codigoPlan: "SP", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "SQ", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "SR", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "SS", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "ST", tipo: "EMPRESA CONTROLADA $0.07/0.14"},
	{codigoPlan: "SY", tipo: "EMPRESA CUENTA CONTROLADA $0.09"},
	{codigoPlan: "SZ", tipo: "EMPRESA CONTROLADA $0.055/0.14"},
	{codigoPlan: "T0", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "T1", tipo: "INACTIVO"},
	{codigoPlan: "T2", tipo: "INACTIVO"},
	{codigoPlan: "T3", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "T4", tipo: "EMPRESA CONTROLADA $0.065/0.14"},
	{codigoPlan: "T5", tipo: "EMPRESA C.CONTROLADA $0.075"},
	{codigoPlan: "T6", tipo: "EMPRESA C.CONTROLADA $0.05/0.14"},
	{codigoPlan: "T7", tipo: "INACTIVO"},
	{codigoPlan: "T8", tipo: "INACTIVO"},
	{codigoPlan: "T9", tipo: "INACTIVO"},
	{codigoPlan: "TA", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "TB", tipo: "EMPRESA CUENTA CONTROLADA $0.06"},
	{codigoPlan: "TC", tipo: "EMPRESA CONTROLADA $0.055/0.13"},
	{codigoPlan: "TD", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "TE", tipo: "EMPRESA CUENTA CONTROLADA"},
	{codigoPlan: "TF", tipo: "TODO INCLUIDO CUENTA CONTROLADA"},
	{codigoPlan: "TG", tipo: "ECONOMICO CUENTA CONTROLADA"},
	{codigoPlan: "TH", tipo: "SALTA CUENTA CONTROLADA"},
	{codigoPlan: "TI", tipo: "EMPRESA CONTROLADA $0.045/$0.13"},
	{codigoPlan: "TJ", tipo: "SUPERIOR CUENTA CONTROLADA"},
	{codigoPlan: "TK", tipo: "ILIMITADO CUENTA CONTROLADA"},
	{codigoPlan: "TL", tipo: "FIJO CUENTA CONTROLADA"},
	{codigoPlan: "TM", tipo: "FIJO CUENTA CONTROLADA"},
	{codigoPlan: "TS", tipo: "PREPAGO DATOS UMTS INTERNET"},
	{codigoPlan: "TT", tipo: "EMPRESA FAMILIAR $0.0015"},
	{codigoPlan: "TY", tipo: "EMPRESA CUENTA CONTROLADA $0.13"},
	{codigoPlan: "TZ", tipo: "EMPRESA CUENTA CONTROLADA $0.12"},
	{codigoPlan: "CE", tipo: "EMPRESA FAMILIAR $0.0013"},
	{codigoPlan: "BA", tipo: "PARRANDERO CUENTA CONTROLADA"},
	{codigoPlan: "BB", tipo: "FIJO CUENTA CONTROLADA"},
	{codigoPlan: "B8", tipo: "EMPRESA CUENTA CONTROLADA $0.09"},
	{codigoPlan: "B9", tipo: "EMPRESA CUENTA CONTROLADA $0.07"},
	{codigoPlan: "EA", tipo: "FIJO CUENTA CONTROLADA"},
	{codigoPlan: "CC", tipo: "EMPRESA CUENTACONTROLADA $0.065"},
	{codigoPlan: "PA", tipo: "EMPRESA CUENTA CONTROLADA $0.13"},
	{codigoPlan: "PB", tipo: "EMPRESA CUENTA CONTROLADA $0.12"},
	{codigoPlan: "PC", tipo: "EMPRESA CUENTA CONTROLADA $0.11"},
	{codigoPlan: "PD", tipo: "EMPRESA CUENTA CONTROLADA $0.10"},
	{codigoPlan: "UA", tipo: "EMPRESA CUENTA CONTROLADA $0.09"},
	{codigoPlan: "B4", tipo: "TARIFA UNICA CUENTA CONTROLADA"},
	{codigoPlan: "B6", tipo: "TARIFA UNICA CUENTA CONTROLADA"},
	{codigoPlan: "B5", tipo: "PREPAGO FIJO"},
	{codigoPlan: "B7", tipo: "FIJO CUENTA CONTROLADA"},
	{codigoPlan: "UB", tipo: "PREPAGO PARA POLICIA NACIONAL"},
	{codigoPlan: "TQ", tipo: "EMPRESA C.CONTROLADA $0.065"},
	{codigoPlan: "TN", tipo: "EMPRESA CUENTA CONTROLADA $0.09"},
	{codigoPlan: "TO", tipo: "EMPRESA CUENTA CONTROLADA $0.08"},
	{codigoPlan: "TP", tipo: "EMPRESA CUENTA CONTROLADA $0.07"},
	{codigoPlan: "TR", tipo: "EMPLEADO CUENTA CONTROLADA"},
	{codigoPlan: "UC", tipo: "EMPRESA CUENTA CONTROLADA $0.08"},
	{codigoPlan: "V0", tipo: "EMPLEADO POSPAGO AA"},
	{codigoPlan: "V1", tipo: "TODO INCLUIDO POSPAGO AA"},
	{codigoPlan: "Y1", tipo: "Oficina Movil Conectada"},	
	{codigoPlan: "Y2", tipo: "CC EMPRESAS TODO INCLUIDO"},
	{codigoPlan: "Y5", tipo: "Todo Incluido 3.0"},
	{codigoPlan: "Y8", tipo: "Superior 3.0"},
	{codigoPlan: "Y9", tipo: "No description"},
	{codigoPlan: "TX", tipo: "TODO INCLUIDO CUENTA CONTROLADA"},
	{codigoPlan: "Y3", tipo: "CC Internet Fijo LTE"},
	{codigoPlan: "FH", tipo: "OFICINA FIJA CONECTADA H"},
	{codigoPlan: "C0", tipo: "INDIVIDUAL CUENTA CONTROLADA"},
	{codigoPlan: "C4", tipo: "INACTIVO"},
	{codigoPlan: "D1", tipo: "INDIVIDUAL CUENTA CONTROLADA"},
	{codigoPlan: "D2", tipo: "INDIVIDUAL CUENTA CONTROLADA"},
	{codigoPlan: "D3", tipo: "INDIVIDUAL CUENTA CONTROLADA"},
	{codigoPlan: "D5", tipo: "INACTIVO"},
	{codigoPlan: "D6", tipo: "INACTIVO"},
	{codigoPlan: "D7", tipo: "INACTIVO"},
	{codigoPlan: "N0", tipo: "PREPAGO CLASICO"},
	{codigoPlan: "N3", tipo: "INACTIVO"},
	{codigoPlan: "N4", tipo: "INACTIVO"},
	{codigoPlan: "N7", tipo: "PREPAGO PARRANDERO PAQUETIZADO"},
	{codigoPlan: "N8", tipo: "EMPRESA CUENTA CONTROLADA $0.08"},
	{codigoPlan: "N9", tipo: "ZONA MOVISTAR SMS ILIMITADO"},
	{codigoPlan: "P0", tipo: "PARRANDERO CUENTA CONTROLADA"},
	{codigoPlan: "P1", tipo: "INACTIVO"},
	{codigoPlan: "PP", tipo: "Recargas Externas PPAS"},
	{codigoPlan: "E0", tipo: "CANJE CUENTA CONTROLADA"},
	{codigoPlan: "E1", tipo: "EMPRESA CUENTA CONTROLADA $0.12"},
	{codigoPlan: "E2", tipo: "EMPRESA CUENTA CONTROLADA $0.10"},
	{codigoPlan: "E3", tipo: "EMPRESA CUENTA CONTROLADA $0.05"},
	{codigoPlan: "E4", tipo: "SALTA CUENTA CONTROLADA"},
	{codigoPlan: "E5", tipo: "PREPAGO FIJO ECONOMICO"},
	{codigoPlan: "E6", tipo: "LIBRE CUENTA CONTROLADA"},
	{codigoPlan: "E7", tipo: "FAMILIAR CUENTA CONTROLADA"},
	{codigoPlan: "E8", tipo: "FAMILIAR CUENTA CONTROLADA"},
	{codigoPlan: "E9", tipo: "EMPRESA COMPARTIDO $0.07/$0.13"},
	{codigoPlan: "F0", tipo: "INACTIVO"},
	{codigoPlan: "F1", tipo: "OFICINA FIJA CONECTADA"},
	{codigoPlan: "F2", tipo: "INACTIVO"},
	{codigoPlan: "F3", tipo: "INACTIVO"},
	{codigoPlan: "F4", tipo: "INACTIVO"},
	{codigoPlan: "F5", tipo: "PREPAGO LIBRE"},
	{codigoPlan: "F6", tipo: "EMPRESA CUENTA CONTROLADA $0.15"},
	{codigoPlan: "F7", tipo: "EMPRESA CUENTA CONTROLADA $0.14"},
	{codigoPlan: "F8", tipo: "EMP. CONTROL $0.07/$0.15/$0.043"},
	{codigoPlan: "F9", tipo: "INACTIVO"},
	{codigoPlan: "G0", tipo: "EMPRESA CUENTA CONTROLADA $0.10"},
	{codigoPlan: "G1", tipo: "EMPRESA CUENTA CONTROLADA $0.11"},
	{codigoPlan: "G2", tipo: "EMPRESA CUENTA CONTROLADA $0.12"},
	{codigoPlan: "G3", tipo: "EMPRESA CUENTA CONTROLADA $0.13"},
	{codigoPlan: "G4", tipo: "EMPRESA CUENTA CONTROLADA $0.14"},
	{codigoPlan: "G5", tipo: "EMPRESA CUENTA CONTROLADA $0.15"},
	{codigoPlan: "G6", tipo: "EMPRESA CUENTA CONTROLADA $0.16"},
	{codigoPlan: "G7", tipo: "EMPRESA CUENTA CONTROLADA $0.17"},
	{codigoPlan: "G8", tipo: "EMPRESA CUENTA CONTROLADA $0.18"},
	{codigoPlan: "H0", tipo: "EMPRESA CUENTA CONTROLADA PROMO"},
	{codigoPlan: "H1", tipo: "EMPRESA CUENTA CONTROLADA PROMO"},
	{codigoPlan: "H2", tipo: "EMPRESA CUENTA CONTROLADA PROMO"},
	{codigoPlan: "H3", tipo: "INACTIVO"},
	{codigoPlan: "H4", tipo: "INACTIVO"},
	{codigoPlan: "H5", tipo: "INACTIVO"},
	{codigoPlan: "H6", tipo: "INACTIVO"},
	{codigoPlan: "H7", tipo: "INACTIVO"},
	{codigoPlan: "H8", tipo: "INACTIVO"},
	{codigoPlan: "I0", tipo: "INACTIVO"},
	{codigoPlan: "I1", tipo: "INACTIVO"},
	{codigoPlan: "I2", tipo: "INACTIVO"},
	{codigoPlan: "I3", tipo: "INACTIVO"},
	{codigoPlan: "I4", tipo: "INACTIVO"},
	{codigoPlan: "I5", tipo: "INACTIVO"},
	{codigoPlan: "I6", tipo: "INACTIVO"},
	{codigoPlan: "I7", tipo: "INACTIVO"},
	{codigoPlan: "I8", tipo: "INACTIVO"},
	{codigoPlan: "J0", tipo: "INACTIVO"},
	{codigoPlan: "J1", tipo: "INACTIVO"},
	{codigoPlan: "J2", tipo: "INACTIVO"},
	{codigoPlan: "J3", tipo: "INACTIVO"},
	{codigoPlan: "J4", tipo: "INACTIVO"},
	{codigoPlan: "J5", tipo: "EMPRESA CUENTA CONTROLADA T5"},
	{codigoPlan: "J6", tipo: "INACTIVO"},
	{codigoPlan: "J7", tipo: "INACTIVO"},
	{codigoPlan: "J8", tipo: "INACTIVO"},
	{codigoPlan: "K0", tipo: "INACTIVO"},
	{codigoPlan: "K1", tipo: "INACTIVO"},
	{codigoPlan: "K2", tipo: "INACTIVO"},
	{codigoPlan: "K3", tipo: "INACTIVO"},
	{codigoPlan: "K4", tipo: "INACTIVO"},
	{codigoPlan: "K5", tipo: "INACTIVO"},
	{codigoPlan: "K6", tipo: "INACTIVO"},
	{codigoPlan: "K7", tipo: "INACTIVO"},
	{codigoPlan: "K8", tipo: "INACTIVO"},
	{codigoPlan: "L0", tipo: "INACTIVO"},
	{codigoPlan: "L1", tipo: "INACTIVO"},
	{codigoPlan: "L2", tipo: "INACTIVO"},
	{codigoPlan: "L3", tipo: "INACTIVO"},
	{codigoPlan: "L4", tipo: "INACTIVO"},
	{codigoPlan: "L5", tipo: "INACTIVO"},
	{codigoPlan: "L6", tipo: "INACTIVO"},
	{codigoPlan: "L7", tipo: "INACTIVO"},
	{codigoPlan: "L8", tipo: "INACTIVO"},
	{codigoPlan: "M0", tipo: "INACTIVO"},
	{codigoPlan: "M1", tipo: "INACTIVO"}
];

